name: Generate Documentation

on:
  push:
    branches:
      - main
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up yq and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          wget https://github.com/mikefarah/yq/releases/download/v4.15.1/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Load and merge YAML files into hots
        run: |
          IFS=',' read -ra SORT_FILES <<< "${{ secrets.SECRET_SORT }}"
          HOTS="[]"
          HOT_LIST="[]"
          for SORT in "${SORT_FILES[@]}"; do
            FILE_PATH="docs/${SORT}.yml"
            if [ -f "$FILE_PATH" ]; then
              FILE_CONTENT=$(yq eval -o=json "$FILE_PATH")
              HOTS=$(jq --argjson new_item "$FILE_CONTENT" \
                        '$HOT_LIST + [$new_item]' <<< "$HOTS")
            else
              echo "Warning: File $FILE_PATH does not exist."
            fi
          done
          echo "hots=$HOTS" >> $GITHUB_ENV

      - name: Create all.json
        run: |
          yq eval -o=json 'docs/*.yml' . > output/all.json

      - name: Process and combine data
        run: |
          jq --argjson hots "$HOTS" \
             '{ hots: $hots, items: (.rest | group_by(.category) | map({ (.[0].category): . }) | add)}' \
             output/all.json > output/combined.json

      - name: Convert JSON to YAML
        run: |
          yq eval -P -o=yaml output/combined.json > output/combined.yaml

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          branch: gh-pages
          folder: output