name: Build and Publish

on:
  push:
    branches: [ main ]
    # paths:
    #   - 'docs/*.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: install-jq
        run: |
          sudo apt-get update && sudo apt-get install -y jq

      - name: read_hot_sorts
        id: hot
        run: |
          HOTS="${{ secrets.SECRET_SORT }}"
          echo "hot_sorts=$HOTS" >> $GITHUB_OUTPUT

      - name: merge_docs_to_json
        run: |
          mkdir -p output
          yq eval-all -o=json '[.]' docs/*.yml > output/all.json

      - name: extract_hot_and_rest
        run: |
          HOTS="${{ steps.hot.outputs.hot_sorts }}"
          IFS=',' read -ra HOT_ARRAY <<< "$HOTS"
          HOT_JSON=$(jq -n --argjson inp "$(cat output/all.json)" \
            --argjson hotlist "$(printf '%s\n' "${HOT_ARRAY[@]}" | jq -R -s -c 'split("\n")[:-1]')" \
            '{hot: ($inp | map(select(.sort as $s | $hotlist | index($s)))) , rest: ($inp | map(select(.sort as $s | $hotlist | index($s) | not)))}')
          echo "$HOT_JSON" > output/parted.json

      - name: group_items_by_category
        run: |
          jq '{hot: .hot, items: (.rest | group_by(.category) | map({ (.[0].category): . }) | add)}' output/parted.json > output/combined.json
          yq eval -P output/combined.json > output/combined.yaml

      - name: prepare_site
        run: |
          mkdir site
          cp output/combined.json site/
          cp output/combined.yaml site/

      - name: upload_pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deploy
        uses: actions/deploy-pages@v4
